# Generated by Django 3.2.19 on 2023-07-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
                ('birth', models.DateField(default=None)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='condition_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='market_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sector_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=6, unique=True)),
                ('stock_name', models.CharField(max_length=50)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.market_type')),
            ],
        ),
        migrations.CreateModel(
            name='upjong_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upjong_name', models.CharField(max_length=50, unique=True)),
                ('upjong_description', models.CharField(max_length=1000)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sector_type')),
            ],
        ),
        migrations.CreateModel(
            name='upjong_of_stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.stock_info')),
                ('upjong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.upjong_type')),
            ],
        ),
        migrations.CreateModel(
            name='theme_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=50, unique=True)),
                ('theme_description', models.CharField(max_length=1000)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sector_type')),
            ],
        ),
        migrations.CreateModel(
            name='theme_of_stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.stock_info')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.theme_type')),
            ],
        ),
        migrations.CreateModel(
            name='price_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=0)),
                ('open_price', models.FloatField(default=0)),
                ('high_price', models.FloatField(default=0)),
                ('low_price', models.FloatField(default=0)),
                ('close_price', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.stock_info')),
            ],
        ),
        migrations.CreateModel(
            name='money_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=0, unique=True)),
                ('cum_money', models.BigIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sector_type')),
            ],
        ),
        migrations.CreateModel(
            name='interested_sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(default=0)),
                ('to_date', models.DateField(default=0)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.account')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.condition_list')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sector_type')),
            ],
        ),
        migrations.CreateModel(
            name='interested_alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=0)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.account')),
                ('interested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.interested_sector')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.stock_info')),
            ],
        ),
    ]
